# Generated by Django 2.1.2 on 2018-10-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0002_auto_20181026_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultados',
            new_name='Resultado',
        ),
    ]
