# Generated by Django 2.1.2 on 2018-10-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0003_auto_20181026_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='alumno',
            new_name='zero',
        ),
    ]
