# Generated by Django 2.1.2 on 2018-10-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0004_auto_20181026_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='zero',
            new_name='alumno',
        ),
    ]
